# theme specific configuration (borders, colors)

border_width = 0
default_border_color = '#191724'
floating_border_color = '#191724'
focused_border_color = '#26233a'
margin = 0
workspace_margin = 0

# to leave room for the sidebar
[[gutter]]
side = "Bottom"
value = 40
