#!/usr/bin/env bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &> /dev/null &

  backup $HOME/.config/picom.conf
  cp $SCRIPTPATH/other_themes/picom.conf $HOME/.config/picom.conf
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

# Start other applications

## Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/wallpapers/fennix.png
fi

## Bar
if [ -x "$(command -v eww)" ]; then
  eww -c $SCRIPTPATH/eww open bar
fi

## Compose Key
if [ -x "$(command -v setxkbmap)" ]; then
  setxkbmap -option compose:ralt
fi

backup() {
  cat $1 | grep "NOBACKUP"
  # if NOBACKUP is not found, back up the file
  if [ $? -ne 0 ]; then
    timestamp=$(date +"%s")
    mv $1 $1.$timestamp.backup
  fi
}

if [[ -x "$(command -v kitty)" && -f "$HOME/.config/kitty/kitty.conf" ]]; then
  backup $HOME/.config/kitty/kitty.conf
  cp $SCRIPTPATH/other_themes/kitty.conf $HOME/.config/kitty/kitty.conf
fi

if [ -x "$(command -v firefox)" ] && [ -d $HOME/.mozilla/firefox/*.default-release/chrome/ ]; then
  backup $HOME/.mozilla/firefox/*.default-release/chrome/colors.css
  (cd $HOME/.mozilla/firefox/*.default-release/chrome/ && cp $SCRIPTPATH/other_themes/colors.css colors.css)
fi

if [[ -x "$(command -v dunst)" && -f "$HOME/.config/dunst/dunstrc" ]]; then
  backup $HOME/.config/dunst/dunstrc
  cp $SCRIPTPATH/other_themes/dunstrc $HOME/.config/dunst/dunstrc

  killall dunst && dunst &
fi

if [[ -x "$(command -v stalonetray)" && -f "$HOME/.config/stalonetrayrc" ]]; then
  backup $HOME/.config/stalonetrayrc
  cp $SCRIPTPATH/other_themes/stalonetrayrc $HOME/.config/stalonetrayrc
  stalonetray &
fi

if [[ -x "$(command -v gdbus)" ]]; then
  $SCRIPTPATH/theme-locker.sh > /tmp/theme-locker-log &
fi
