#!/bin/bash

# Edited version of:
# https://github.com/Axarva/dotfiles-2.0/blob/main/config/eww-1920/scripts/getweather

## Collect data
cache_dir="$HOME/.cache/eww/weather"
cache_weather=${cache_dir}/weather-full
cache_loc=${cache_dir}/ip-loc

## Weather data
KEY=`cat $HOME/.openapi_weather_key`
UNIT="imperial"	# Available options : 'metric' or 'imperial'

## Make cache dir
if [[ ! -d "$cache_dir" ]]; then
	mkdir -p ${cache_dir}
fi

## Get data
get_weather_data() {
	ip=`curl -s https://ipinfo.io/ip`
	ipinfo=`curl -s http://ip-api.com/json/"$ip"`
	echo $ipinfo > ${cache_loc}
	lat=`echo "$ipinfo" | jq ".lat"`
	lon=`echo "$ipinfo" | jq ".lon"`
	
	weather=`curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID="$KEY"&lat="$lat"&lon="$lon"&units="$UNIT""`
	echo ${weather}
	echo ${weather} > ${cache_weather}
}

read_weather_data() {
	weather=`cat ${cache_weather}`
	loc=`cat ${cache_loc}`
	if [ ! -z "$weather" ]; then
		weather_temp=`echo "$weather" | jq ".main.temp" | cut -d "." -f 1`
		weather_icon_code=`echo "$weather" | jq -r ".weather[].icon" | head -1`
		weather_description=`echo "$weather" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g"`
		weather_city=`echo "$loc" | jq -r ".city"`

		#Big long if statement of doom
		if [ "$weather_icon_code" == "50d"  ]; then
			weather_icon=" "
			weather_quote="Forecast says it's misty \nMake sure you don't get lost on your way..."
			weather_hex="#c7c7c7"
		elif [ "$weather_icon_code" == "50n"  ]; then
			weather_icon=" "
			weather_quote="Forecast says it's a misty night \nDon't go anywhere tonight or you might get lost..."
			weather_hex="#c7c7c7"
		elif [ "$weather_icon_code" == "01d"  ]; then
			weather_icon=" "
			weather_quote="It's a sunny day, gonna be fun! \nDon't go wandering all by yourself though..."
			weather_hex="#fad07b"
		elif [ "$weather_icon_code" == "01n"  ]; then
			weather_icon=" "
			weather_quote="It's a clear night \nYou might want to take a evening stroll to relax..."
			weather_hex="#73d0ff"
		elif [ "$weather_icon_code" == "02d"  ]; then
			weather_icon=" "
			weather_quote="It's  cloudy, sort of gloomy \nYou'd better get a book to read..."
			weather_hex="#73d0ff"
		elif [ "$weather_icon_code" == "02n"  ]; then
			weather_icon=" "
			weather_quote="It's a cloudy night \nHow about some hot chocolate and a warm bed?"
			weather_hex="#73d0ff"
		elif [ "$weather_icon_code" == "03d"  ]; then
			weather_icon=" "
			weather_quote="It's  cloudy, sort of gloomy \nYou'd better get a book to read..."
			weather_hex="#73d0ff"
		elif [ "$weather_icon_code" == "03n"  ]; then
			weather_icon=" "
			weather_quote="It's a cloudy night \nHow about some hot chocolate and a warm bed?"
			weather_hex="#73d0ff"
		elif [ "$weather_icon_code" == "04d"  ]; then
			weather_icon=" "
			weather_quote="It's  cloudy, sort of gloomy \nYou'd better get a book to read..."
			weather_hex="#73d0ff"
		elif [ "$weather_icon_code" == "04n"  ]; then
			weather_icon=" "
			weather_quote="It's a cloudy night \nHow about some hot chocolate and a warm bed?"
			weather_hex="#73d0ff"
		elif [ "$weather_icon_code" == "09d"  ]; then
			weather_icon=" "
			weather_quote="It's rainy, it's a great day! \nGet some ramen and watch as the rain falls..."
			weather_hex="#fad07b"
		elif [ "$weather_icon_code" == "09n"  ]; then
			weather_icon=" "
			weather_quote=" It's gonna rain tonight it seems \nMake sure your clothes aren't still outside..."
			weather_hex="#fad07b"
		elif [ "$weather_icon_code" == "10d"  ]; then
			weather_icon=" "
			weather_quote="It's rainy, it's a great day! \nGet some ramen and watch as the rain falls..."
			weather_hex="#fad07b"
		elif [ "$weather_icon_code" == "10n"  ]; then
			weather_icon=" "
			weather_quote=" It's gonna rain tonight it seems \nMake sure your clothes aren't still outside..."
			weather_hex="#fad07b"
		elif [ "$weather_icon_code" == "11d"  ]; then
			weather_icon=" "
			weather_quote="There's storm for forecast today \nMake sure you don't get blown away..."
			weather_hex="#ffd580"
		elif [ "$weather_icon_code" == "11n"  ]; then
			weather_icon=" "
			weather_quote="There's gonna be storms tonight \nMake sure you're warm in bed and the windows are shut..."
			weather_hex="#ffd580"
		elif [ "$weather_icon_code" == "13d"  ]; then
			weather_icon=" "
			weather_quote="It's gonna snow today \nYou'd better wear thick clothes and make a snowman as well!"
			weather_hex="#d9d7ce"
		elif [ "$weather_icon_code" == "13n"  ]; then
			weather_icon=" "
			weather_quote="It's gonna snow tonight \nMake sure you get up early tomorrow to see the sights..."
			weather_hex="#d9d7ce"
		elif [ "$weather_icon_code" == "40d"  ]; then
			weather_icon=" "
			weather_quote="Forecast says it's misty \nMake sure you don't get lost on your way..."
			weather_hex="#c7c7c7"
		elif [ "$weather_icon_code" == "40n"  ]; then
			weather_icon=" "
			weather_quote="Forecast says it's a misty night \nDon't go anywhere tonight or you might get lost..."
			weather_hex="#c7c7c7"
		else 
			weather_icon=" "
			weather_quote="Sort of odd, I don't know what to forecast \nMake sure you have a good time!"
			weather_hex="#adadff"
		fi
	else
		weather_stat="Weather Unavailable"
		weather_icon=" "
		weather_quote="Ah well, no weather huh? \nEven if there's no weather, it's gonna be a great day!"
		weather_degree="-"
		weather_hex="#adadff"
		weather_city="Unknown Location"
	fi
}

## Execute
for arg in "$@"
do
	case $arg in
		"--getdata" )
			get_weather_data
			;;
		"--icon" )
			read_weather_data
			echo ${weather_icon}
			;;
		"--temp" )
			read_weather_data
			echo ${weather_temp}"°F"
			;;
		"--hex" )
			read_weather_data
			echo ${weather_hex}
			;;
		"--stat" )
			read_weather_data
			echo ${weather_description}
			;;
		"--quote" )
			read_weather_data
			echo -e ${weather_quote} | head -n1
			;;
		"--quote2" )
			read_weather_data
			echo -e ${weather_quote} | tail -n1
			;;
		"--city" )
			read_weather_data
			echo ${weather_city}
			;;
	esac
done
